package com.tanrunn.buildshop.client;

import com.tanrunn.buildshop.network.BuildShopNetwork.ProductDto;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.TagParser;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.core.registries.BuiltInRegistries;

/** Resolves server-sent item SNBT without linking shared logic to ApricityUI. */
public final class ClientItemStackResolver {
    private ClientItemStackResolver() {
    }

    public static ItemStack resolve(ProductDto product) {
        if (product == null || product.isEntityProduct()) return ItemStack.EMPTY;
        ItemStack parsed = parse(product.itemExpression());
        if (!parsed.isEmpty()) return parsed;
        return fallback(product.itemId());
    }

    /**
     * Parses the canonical ItemStack SNBT generated by ItemStack.CODEC. A plain item id is also
     * accepted for compatibility with older servers and hand-authored test payloads.
     */
    public static ItemStack parse(String expression) {
        if (expression == null || expression.isBlank()) return ItemStack.EMPTY;
        try {
            CompoundTag tag = TagParser.parseTag(expression);
            return ItemStack.CODEC.parse(NbtOps.INSTANCE, tag).result().orElse(ItemStack.EMPTY);
        } catch (Exception ignored) {
            return fallback(expression);
        }
    }

    private static ItemStack fallback(String itemId) {
        if (itemId == null || itemId.isBlank()) return ItemStack.EMPTY;
        ResourceLocation id = ResourceLocation.tryParse(itemId.trim());
        if (id == null || !BuiltInRegistries.ITEM.containsKey(id)) return ItemStack.EMPTY;
        return new ItemStack(BuiltInRegistries.ITEM.get(id));
    }
}
